name: flow-1

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'

jobs:
  validate-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch + validate secret
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}   # must exist in repo/org secrets
        run: |
          if [ -z "${GITHUB_USERNAME:-}" ]; then
            echo "Secret USERNAME is missing or not available to this event."
            exit 1
          fi
          echo "Secret present (length: ${#GITHUB_USERNAME})"   # value will be masked as ***

  deploy:
    needs: validate-secret
    uses: ./.github/workflows/resuable.yml   # calling a reusable workflow (job-level 'uses')
    secrets: inherit                          # pass all calling-job secrets to the reusable workflow
    # with:
    #   some_input: "value"                   # if your reusable workflow defines inputs
