name: flow-1
on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#     branches:
#         - main
#         - develop
#         - 'feature/*'
  push:
    branches:
        - main
    paths-ignore:
      - '.github/workflows/**'

jobs:
  run-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Hello, GitHub Actions! -- will be triggered on push to main branch" 