name: flow-1

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'

jobs:
  run-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch + validate secret
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}   # your repo/Org secret
        run: |
          if [ -z "${GITHUB_USERNAME:-}" ]; then
            echo " Secret USERNAME is missing or not available to this event."
            exit 1
          fi
          echo "Secret present (length: ${#GITHUB_USERNAME})"   # value will be masked if echoed

      - name: calling reusable
        uses: ./.github/workflows/resuable.yml

      # - name: Produce artifact
      #   run: |
      #     mkdir -p out
      #     printf "Hello from %s\n" "$(date -u +'%Y-%m-%d %H:%M:%S UTC')" > out/hello.txt

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: hello-artifact
      #     path: out/
      #     if-no-files-found: error     # change to warn/ignore if you don’t want failure
      #     retention-days: 7


