name: flow-1
on:
#   push:
#     branches:
#       - main
  pull_request:
    branches:
      - main

jobs:
  run-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Hello, GitHub Actions!"